import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/common/Sidebar";
import RightPanel from "@/components/common/RightPanel";
import ClientProvider from "@/lib/ClientProvider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twitter",
  description: "Generated by Elon Musk",
};


export default function RootLayout({

  children,
}: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en" data-theme="black">
      <body className={inter.className}>
        <div className="container mx-auto flex min-h-screen">
          <Sidebar />
          <main className="flex-1">
            <ClientProvider>
            <Toaster />
            {children}

            </ClientProvider>
          </main>
          <RightPanel />
        </div>
      </body>
    </html>
  );
}
